# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'InitiumTest2' do
    
  pod 'SnapKit', '~> 3.1.2'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']

end
